# appveyor file:
# http://www.appveyor.com/docs/appveyor-yml
# http://www.appveyor.com/docs/environment-variables

version: "{build}"

# blacklist
#except:
#  - gh-pages

build: false

environment:
    matrix:
        - PYTHON: "C:/Python27"
        - PYTHON: "C:/Python34"

platform:
    - AnyCPU

init:
    - echo %PYTHON%
    - ps: "ls C:/Python*"
    - set

# clone directory
clone_folder: c:/bootstrap_env_clone

# set clone depth
clone_depth: 5 # clone entire repository history if not defined

install:
    - set ENV_DIR=C:/bootstrap_env
    - echo "boot into: '%ENV_DIR%'..."
    - "%PYTHON%/python.exe c:/bootstrap_env_clone/bootstrap_env/boot.py %ENV_DIR% --install_type git_readonly"
    - cd %ENV_DIR%
    - call Scripts/activate.bat
    - cd src/bootstrap-env
    - git checkout -qf %APPVEYOR_REPO_COMMIT%

test_script:
    - coverage run ./setup.py nosetests
    - coveralls
