# appveyor file:
# http://www.appveyor.com/docs/appveyor-yml
# http://www.appveyor.com/docs/environment-variables

version: "{build}"

# blacklist
#except:
#  - gh-pages

build: false

environment:
    global:
      COVERALLS_SERVICE_NAME: AppVeyor
      COVERALLS_REPO_TOKEN:
        secure: NtVDkuJYChPKhQpSQUlKEKg5aVyzeI8no
    matrix:
        - PYTHON: "C:/Python27/python.exe"
        - PYTHON: "C:/Python35/python.exe"

platform:
    - AnyCPU

init:
    - "%PYTHON% --version"
    - ps: "ls C:/Python*"
#    - set

# clone directory
clone_folder: c:/bootstrap_env_clone

# set clone depth
clone_depth: 5 # clone entire repository history if not defined

install:
    - cd %APPVEYOR_BUILD_FOLDER% # c:/bootstrap_env_clone
    - "pip install --upgrade pip"
    - "pip --version"
    - "pip install ."
    - "pip install virtualenv nose coveralls"
    - "pip freeze"

test_script:
    - coverage run ./setup.py nosetests

on_success:
    - coverage combine
    - coverage report
    - coveralls
