# appveyor file:
# http://www.appveyor.com/docs/appveyor-yml
# http://www.appveyor.com/docs/environment-variables

version: "{build}"

# blacklist
#except:
#  - gh-pages

build: false

environment:
    matrix:
        - PYTHON: "C:/Python27/python.exe"
        - PYTHON: "C:/Python35/python.exe"

platform:
    - AnyCPU

init:
    - "%PYTHON% --version"
    - ps: "ls C:/Python*"
#    - set

# clone directory
clone_folder: c:/bootstrap_env_clone

# set clone depth
clone_depth: 5 # clone entire repository history if not defined

install:
    - cd %APPVEYOR_BUILD_FOLDER% # c:/bootstrap_env_clone
    - "pip install --upgrade pip"
    - "pip --version"
    - "pip install ."

#    - "pip install virtualenv nose coveralls"
    - "pip install virtualenv nose"

    # Use a newer Version than v1.1 from PyPi, see:
    # https://github.com/coagulant/coveralls-python/pull/97
    - "pip install https://github.com/coagulant/coveralls-python/archive/master.zip"

    - "pip freeze"

test_script:
    - coverage run --source=bootstrap_env ./setup.py nosetests

after_test:
#    - ps: "ls .coverage"
    - coverage report
    - set COVERALLS_REPO_TOKEN=NtVDkuJYChPKhQpSQUlKEKg5aVyzeI8no
    - coveralls
